spring.neo4j.uri=neo4j+s://b66256f5.databases.neo4j.io
spring.neo4j.authentication.username=b66256f5
spring.neo4j.authentication.password=rbKcSnDl7j-mKaH87SWU3LPeb9J4oLy0zGL6KPLkurA
logging.level.org.springframework=WARN
spring.neo4j.database=b66256f5
logging.level.org.springframework.data.neo4j=ERROR
logging.level.org.neo4j.driver=ERROR
logging.level.org.hibernate=ERROR
